export const APP_NAME = "FF META";
export const APP_TAGLINE = "Fantasy Football Meta";
export const COPYRIGHT = `© ${new Date().getFullYear()} FF META. Fantasy Football Meta Analytics.`;
export const SIDEBAR_WIDTH = 280; // px
export const SIDEBAR_COLLAPSED_WIDTH = 80; // px
export const LOADING_MESSAGE = "Loading your experience...";
export const ERROR_GENERIC = "An unknown error occurred.";
export const ERROR_AUTH = "Authentication Error";
export const RETRY_LABEL = "Retry";
export const LOGIN_LABEL = "Login";
export const SIGNUP_LABEL = "Sign Up";
