// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yhibrugwsqqbujeosxzg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InloaWJydWd3c3FxYnVqZW9zeHpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNjMwNTEsImV4cCI6MjA2NjYzOTA1MX0.NLFp-lfsO2RFi5Pha8IQInypdRnnb5PXAkuzVVwQQI0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);